Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2019-10, with the labels that each got.

#233 Ticket4797 db server low interest p vs
  DatabaseServer/database_server.py
  DatabaseServer/test_modules/test_database_server.py
  server_common/ioc_data_source.py
  server_common/mocks/mock_ioc_data_source.py
  server_common/pv_names.py
  server_common/test_modules/test_ioc_data.py
Labels: size/L

#232 Changes to blockserver to write new sub element to meta.xml
  BlockServer/config/metadata.py
  BlockServer/config/xml_converter.py
  BlockServer/core/config_holder.py
  BlockServer/core/inactive_config_holder.py
  schema/meta.xsd
Labels: size/S, ticket

#238 Make name of method correct
  ReflectometryServer/test_modules/test_beamline_parameter.py
Labels: size/XS

#239 Dont run CAM tests on linux
  CollisionAvoidanceMonitor/test_modules/__init__.py
Labels: size/XS

#237 Ticket4795
  BlockServer/config/xml_converter.py
  BlockServer/core/config_holder.py
  BlockServer/core/config_list_manager.py
  BlockServer/core/inactive_config_holder.py
  BlockServer/mocks/mock_file_manager.py
  BlockServer/test_modules/test_config_list_manager.py
  block_server.py
  server_common/channel_access.py
  server_common/test_modules/test_common_utilities.py
  server_common/utilities.py
Labels: size/L
