Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2019-12, with the labels that each got.

#254 Allow options for disconnected blocks in run control
  BlockServer/config/block.py
  BlockServer/config/configuration.py
  BlockServer/config/xml_converter.py
  BlockServer/core/config_holder.py
  BlockServer/core/constants.py
  BlockServer/runcontrol/runcontrol_manager.py
  BlockServer/test_modules/test_configuration_xml.py
  BlockServer/test_modules/test_runcontrol_manager.py
  schema/blocks.xsd
Labels: size/L

#257 Skip linux build
  BlockServer/test_modules/__init__.py
Labels: size/XS

#244 Ticket3892 refl propagate alarms
  ReflectometryServer/ChannelAccess/pv_manager.py
  ReflectometryServer/ChannelAccess/reflectometry_driver.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/beamline.py
  ReflectometryServer/components.py
  ReflectometryServer/engineering_corrections.py
  ReflectometryServer/example_beamline.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/parameters.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_actual_positions.py
  ReflectometryServer/test_modules/test_beamline.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_components.py
  ReflectometryServer/test_modules/test_engineering_corrections.py
  ReflectometryServer/test_modules/test_ioc_driving_layer.py
  ReflectometryServer/test_modules/test_observable.py
  ReflectometryServer/test_modules/test_set_current_motor_position.py
  server_common/observable.py
Labels: size/XXL

#255 Ticket4127 refl retry adding monitors
  ReflectometryServer/ChannelAccess/pv_manager.py
  ReflectometryServer/ChannelAccess/reflectometry_driver.py
  ReflectometryServer/beamline.py
  ReflectometryServer/beamline_configuration.py
  ReflectometryServer/footprint_manager.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/reflectometry_server.py
  ReflectometryServer/test_modules/test_pv_wrapper.py
Labels: size/L

#258 observable has moved
  ReflectometryServer/components.py
  ReflectometryServer/test_modules/test_observable.py
Labels: size/XS

#256 Ticket4975 refl minimum motor velocity
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_pv_wrapper.py
Labels: size/L

#259 Increase max array bytes
  start_blockserver_cmd.bat
Labels: size/XS
