Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2019-11, with the labels that each got.

#241 Ticket 4899 - Reflectometry: Fix error when DisplcementDriver is created based on a component which is out of the beam
  ReflectometryServer/ioc_driver.py
Labels: size/XS

#243 Fix bug saving floats
  server_common/autosave.py
Labels: size/XS

#245 Add verbosity
  run_all_tests.py
Labels: size/XS

#246 Update Jenkinsfile
  Jenkinsfile
Labels: size/XS

#247 Update Jenkinsfile
  Jenkinsfile
Labels: size/XS

#248 Update Jenkinsfile
  Jenkinsfile
Labels: size/XS

#242 Increase max bytes for block cache
  BlocksCache/blocks_cache.py
  start_block_cache_cmd.bat
Labels: size/XS

#249 Allow unit tests to be run with no genie_python
  RemoteIocServer/test_modules/test_config_monitor.py
  RemoteIocServer/utilities.py
Labels: size/S

#250 fix unicode vs str problem
  BlocksCache/blocks_cache.py
Labels: size/XS

#234 Ticket4588 monitor stall
  ReflectometryServer/file_io.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/reflectometry_server.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_ioc_driving_layer.py
  ReflectometryServer/test_modules/test_pv_wrapper.py
Labels: size/L

#251 Move other genie python into try catch and remove unneeded references
  RemoteIocServer/config_monitor.py
  RemoteIocServer/test_modules/test_config_monitor.py
  RemoteIocServer/utilities.py
Labels: size/XS

#240 Ticket4131 zero motors via beamline parameters
  ReflectometryServer/ChannelAccess/constants.py
  ReflectometryServer/ChannelAccess/pv_manager.py
  ReflectometryServer/ChannelAccess/reflectometry_driver.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/beamline.py
  ReflectometryServer/components.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/movement_strategy.py
  ReflectometryServer/parameters.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/reflectometry_server.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_set_current_motor_position.py
  server_common/channel_access.py
Labels: size/XL

#252 Move all genie python access to channel access wrapper
  RemoteIocServer/config_monitor.py
  RemoteIocServer/utilities.py
  server_common/channel_access.py
Labels: size/M

#253 Fix velocity set loggger message
  ReflectometryServer/pv_wrapper.py
Labels: size/XS
