Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2020-01, with the labels that each got.

#262 If there is no remote pv prefix assume it is Empty not set
  block_server.py
Labels: size/XS

#263 Add EMU
  scripts/set_instrument_list.py
Labels: size/XS

#260 On successful PV write value is sent to put log
  ReflectometryServer/ChannelAccess/reflectometry_driver.py
  server_common/loggers/isis_logger.py
  server_common/test_modules/test_log_writer.py
Labels: size/L

#264 Update Jenkinsfile
  Jenkinsfile
Labels: size/XS

#266 Fix jenkinsfile syntax
  Jenkinsfile
Labels: size/XS

#267 changed max size for macro values to 256 characters
  schema/ioc_types.xsd
Labels: size/XS

#268 Ticket 5140: Allow setting RB number correctly
  DatabaseServer/exp_data.py
  DatabaseServer/test_modules/test_exp_data.py
Labels: size/M

#269 Ticket5140 set rb number
  DatabaseServer/exp_data.py
  DatabaseServer/test_modules/test_exp_data.py
Labels: size/M
