Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2020-06, with the labels that each got.

#297 Ticket 4136: Removed block cache
  BlockServer/core/active_config_holder.py
  BlockServer/core/block_cache_manager.py
  BlocksCache/blocks_cache.py
  README.md
  block_server.py
  start_block_cache_cmd.bat
  stop_block_cache.bat
Labels: size/L

#293 refl to py3
  ReflectometryServer/ChannelAccess/pv_manager.py
  ReflectometryServer/ChannelAccess/reflectometry_driver.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/beamline.py
  ReflectometryServer/components.py
  ReflectometryServer/exceptions.py
  ReflectometryServer/footprint_calc.py
  ReflectometryServer/footprint_manager.py
  ReflectometryServer/geometry.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/movement_strategy.py
  ReflectometryServer/out_of_beam.py
  ReflectometryServer/parameters.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/run_tests.py
  ReflectometryServer/server_status_manager.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_beamline.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_components.py
  ReflectometryServer/test_modules/test_movement.py
  ReflectometryServer/test_modules/test_observable.py
  ReflectometryServer/test_modules/test_pv_wrapper.py
  start_refl_server_cmd.bat
Labels: size/L

#299 Fix tests
  Jenkinsfile
  ReflectometryServer/test_modules/__init__.py
  RemoteIocServer/test_modules/__init__.py
  server_common/test_modules/test_channel_access.py
  server_common/test_modules/test_log_writer.py
Labels: size/M

#300 Fix rh build
  ReflectometryServer/__init__.py
  ReflectometryServer/movement_strategy.py
Labels: size/M

#298 Ticket5432 bench component and parameters
  ReflectometryServer/ChannelAccess/pv_manager.py
  ReflectometryServer/ChannelAccess/reflectometry_driver.py
  ReflectometryServer/__init__.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/beamline.py
  ReflectometryServer/beamline_configuration.py
  ReflectometryServer/beamline_constant.py
  ReflectometryServer/components.py
  ReflectometryServer/config_helper.py
  ReflectometryServer/engineering_corrections.py
  ReflectometryServer/example_beamline.py
  ReflectometryServer/exceptions.py
  ReflectometryServer/footprint_calc.py
  ReflectometryServer/geometry.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/out_of_beam.py
  ReflectometryServer/parameters.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/server_status_manager.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_actual_positions.py
  ReflectometryServer/test_modules/test_beam_path_calc.py
  ReflectometryServer/test_modules/test_beamline.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_components.py
  ReflectometryServer/test_modules/test_config/error_config/refl/config.py
  ReflectometryServer/test_modules/test_config/good_config/refl/config.py
  ReflectometryServer/test_modules/test_config_helper.py
  ReflectometryServer/test_modules/test_engineering_corrections.py
  ReflectometryServer/test_modules/test_ioc_driving_layer.py
  ReflectometryServer/test_modules/test_set_current_motor_position.py
  ReflectometryServer/test_modules/utils.py
Labels: size/XXL
