Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2020-07, with the labels that each got.

#305 Use a dummy logger during tests
  DatabaseServer/test_modules/test_database_server.py
Labels: size/XS

#304 Add initial fix for SOI issue
  BlockServer/epics/gateway.py
  BlockServer/runcontrol/runcontrol_manager.py
  BlockServer/test_modules/test_epics_gateway.py
Labels: size/M

#308 Moves get macros to common
  server_common/helpers.py
Labels: size/S

#302 Ticket5453 engineering correction depend on mode
  ReflectometryServer/ChannelAccess/reflectometry_driver.py
  ReflectometryServer/__init__.py
  ReflectometryServer/beamline.py
  ReflectometryServer/engineering_corrections.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/test_modules/test_engineering_corrections.py
  server_common/observable.py
  server_common/test_modules/test_observable.py
Labels: size/XL

#307 Updating BlockserverToKafka to use new Flatbuffer helpers to construct Forwarder configuration
  BlockServerToKafka/__init__.py
  BlockServerToKafka/block_server_monitor.py
  BlockServerToKafka/forwarder_config.py
  BlockServerToKafka/kafka_producer.py
  BlockServerToKafka/main.py
  BlockServerToKafka/run_tests.py
  BlockServerToKafka/test_modules/__init__.py
  BlockServerToKafka/test_modules/test_block_server_monitor.py
  BlockServerToKafka/test_modules/test_forwarder_config.py
  start_bs_to_kafka_cmd.bat
Labels: size/L

#301 Ticket5456 beam bloker
  ReflectometryServer/ChannelAccess/channel_access_constant.py
  ReflectometryServer/ChannelAccess/driver_utils.py
  ReflectometryServer/ChannelAccess/pv_manager.py
  ReflectometryServer/ChannelAccess/reflectometry_driver.py
  ReflectometryServer/__init__.py
  ReflectometryServer/config_helper.py
  ReflectometryServer/file_io.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/parameters.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_config_helper.py
  ReflectometryServer/test_modules/test_driver_utils.py
  ReflectometryServer/test_modules/test_ioc_driving_layer.py
  server_common/observable.py
  server_common/test_modules/test_observable.py
Labels: size/XXL
