Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2020-05, with the labels that each got.

#290 Ticket4967 refl opi improvements
  ReflectometryServer/__init__.py
  ReflectometryServer/parameters.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_set_current_motor_position.py
Labels: size/L

#289 Ticket4289 config for crisp
  ReflectometryServer/ChannelAccess/pv_manager.py
  ReflectometryServer/__init__.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/beamline.py
  ReflectometryServer/beamline_constant.py
  ReflectometryServer/components.py
  ReflectometryServer/config_helper.py
  ReflectometryServer/exceptions.py
  ReflectometryServer/parameters.py
  ReflectometryServer/reflectometry_server.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_beamline.py
  ReflectometryServer/test_modules/test_components.py
  ReflectometryServer/test_modules/test_config_helper.py
  ReflectometryServer/test_modules/test_engineering_corrections.py
Labels: size/XL

#291 Try moving use of wrapper in
  ReflectometryServer/test_modules/test_config_helper.py
Labels: size/S

#294 Add debug code for rh
  ReflectometryServer/config_helper.py
  ReflectometryServer/run_tests.py
  ReflectometryServer/test_modules/test_config_helper.py
Labels: size/S

#295 Address arguments correctly and remove prints.
  ReflectometryServer/config_helper.py
  ReflectometryServer/test_modules/test_config_helper.py
Labels: size/XS

#292 Ticket 5413: Cset not call blockserver
  BlockServer/core/macros.py
  BlockServer/core/on_the_fly_pv_interface.py
  BlockServer/devices/devices_manager.py
  BlockServer/epics/gateway.py
  BlockServer/runcontrol/runcontrol_manager.py
  BlockServer/synoptic/synoptic_manager.py
  BlockServer/test_modules/test_epics_gateway.py
  BlockServer/test_modules/test_runcontrol_manager.py
  block_server.py
Labels: size/XL

#296 Don't fail if mysql is unavailable
  server_common/helpers.py
Labels: size/S
