Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2020-04, with the labels that each got.

#285 Fix rhel2
  server_common/channel_access.py
Labels: size/S

#283 Ticket4309 refl multiple parked positions
  ReflectometryServer/__init__.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/out_of_beam.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_engineering_corrections.py
  ReflectometryServer/test_modules/test_ioc_driving_layer.py
  ReflectometryServer/test_modules/test_out_of_beam_lookup.py
Labels: size/L

#286 Try not to use CaChannel wrapper in test so it runs on redhat
  server_common/channel_access.py
Labels: size/XS

#276 Rename SUSPEND_ON_INVALID to SOI
  BlockServer/core/constants.py
Labels: size/XS

#282 Allow numbers smaller than 1E-4 for block deadband
  schema/blocks.xsd
Labels: size/XS

#287 Ensure position is set while still in SET context
  ReflectometryServer/pv_wrapper.py
Labels: size/XS

#281 Add microsoft teams connector
  Jenkinsfile
Labels: size/M

#272 Add help to register the start of an ioc
  ReflectometryServer/reflectometry_server.py
  server_common/helpers.py
Labels: size/S

#288 Fix reflectometry server imports
  ReflectometryServer/reflectometry_server.py
Labels: size/XS
