Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2020-08, with the labels that each got.

#303 Ticket3465 bench driver
  server_common/channel_access.py
  server_common/test_modules/test_channel_access.py
Labels: size/M

#311 Make channel access close enough without genie_python to allow tests to pass
  server_common/channel_access.py
Labels: size/S

#310 Restart CAEN every time, regardless whether config has changed enough
  block_server.py
Labels: size/S

#312 Remove wait in set, it isn't needed problem is elsewhere
  server_common/channel_access.py
Labels: size/XS

#314 Add INTER to inst list
  scripts/set_instrument_list.py
Labels: size/XS

#315 add polref
  scripts/set_instrument_list.py
Labels: size/XS

#316 Add SANS2D to inst list
  scripts/set_instrument_list.py
Labels: size/XS
