Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2020-11, with the labels that each got.

#322 change_users() not setting users correctly
  DatabaseServer/exp_data.py
  DatabaseServer/test_modules/test_exp_data.py
Labels: size/L

#321 Adding heartbeat pv
  block_server.py
  server_common/pv_names.py
Labels: size/XS

#325 Ticket5803
  BlockServer/runcontrol/runcontrol_manager.py
  BlockServer/test_modules/test_runcontrol_manager.py
  block_server.py
Labels: size/L

#323 Add groups to inst list
  scripts/set_instrument_list.py
Labels: size/M

#327 Add safe not quick
  server_common/channel_access.py
Labels: size/XS
