Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2021-01, with the labels that each got.

#337 Increase PV array size
  DatabaseServer/database_server.py
Labels: size/XS

#335 Ticket 4876
  scripts/hex_compress_and_put_pv.py
  scripts/instrument_status.py
  scripts/set_instrument_list.py
Labels: size/M

#336 Ticket 2185: Updated pr template
  PULL_REQUEST_TEMPLATE.md
Labels: size/XS

#341 Fix remoteioc tests
  RemoteIocServer/test_modules/test_config_monitor.py
Labels: size/XS

#342 Only push on branches with the same name as your machine
  ConfigVersionControl/git_version_control.py
  ConfigVersionControl/test_modules/test_version_contol.py
Labels: size/S

#328 Only search for valid block syntax
  BlockServer/epics/gateway.py
  BlockServer/runcontrol/runcontrol_manager.py
  BlockServer/test_modules/test_epics_gateway.py
Labels: size/M
