Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2021-02, with the labels that each got.

#345 Move MySql abstraction layer to genie and rename
  ArchiverAccess/archiver_access.py
  ArchiverAccess/archiver_data_source.py
  ArchiverAccess/logging_period_providers.py
  ArchiverAccess/test_modules/test_archiver_data_source.py
  ArchiverAccess/test_modules/test_log_period_provider.py
  DatabaseServer/database_server.py
  DatabaseServer/exp_data.py
  scripts/log_file_generator.py
  server_common/helpers.py
  server_common/ioc_data_source.py
  server_common/mysql_abstraction_layer.py
  server_common/test_modules/test_ioc_data_source.py
Labels: size/L

#343 adding musr to instlist
  scripts/set_instrument_list.py
Labels: size/XS

#346 Blockserver synoptics: handle bytes and string correctly
  BlockServer/fileIO/schema_checker.py
  BlockServer/synoptic/synoptic_manager.py
  BlockServer/test_modules/test_synoptic_manager.py
Labels: size/M

#326 Ticket5069
  BlockServer/config/metadata.py
  BlockServer/config/xml_converter.py
  BlockServer/core/active_config_holder.py
  BlockServer/core/config_holder.py
  BlockServer/core/inactive_config_holder.py
  BlockServer/epics/archiver_manager.py
  BlockServer/epics/gateway.py
  BlockServer/run_tests.py
  BlockServer/runcontrol/runcontrol_manager.py
  BlockServer/test_modules/settings/non_empty/block_config.xml
  BlockServer/test_modules/settings/non_empty/gwblock.pvlist
  BlockServer/test_modules/test_active_config_holder.py
  BlockServer/test_modules/test_archiver_manager.py
  BlockServer/test_modules/test_config_list_manager.py
  BlockServer/test_modules/test_configuration_xml.py
  BlockServer/test_modules/test_epics_gateway.py
  BlockServer/test_modules/test_runcontrol_manager.py
  block_server.py
  schema/meta.xsd
Labels: size/L

#348 Make sure all tests are running
  BlockServer/run_tests.py
Labels: size/XS

#349 Fix build
  CollisionAvoidanceMonitor/collide.py
  CollisionAvoidanceMonitor/move.py
  RemoteIocServer/test_modules/test_config_monitor.py
Labels: size/XS

#347 Add constant
  server_common/ioc_data_source.py
Labels: size/XS

#350 Added HRPD_SETUP to inst list
  scripts/set_instrument_list.py
Labels: size/XS

#196 Add event script
  ArchiverAccess/archiver_data_source.py
  scripts/log_event_generator.py
  scripts/log_file_generator.py
  scripts/restore_motor_positions.py
  server_common/helpers.py
  server_common/utilities.py
Labels: size/L

#352 Disable running python2 tests
  Jenkinsfile
Labels: size/XS

#353 Actually use python3 not python2 for python 3 tests
  Jenkinsfile
Labels: size/XS
