Repository ISISComputingGroup/EPICS-inst_servers, pull requests merged in 2022-03, with the labels that each got.

#359 Print message to console on logger connect failure
  server_common/loggers/isis_logger.py
Labels: size/XS

#360 Fix incorrect warnings printed; remove code duplication
  scripts/set_instrument_list.py
Labels: size/M

#361 retry block xml upload
  BlockServer/epics/archiver_manager.py
Labels: size/S

#362 retry connection rather than quitting if broker not found/server not …
  BlockServerToKafka/kafka_producer.py
Labels: size/S

#363 Use subprocess.run to avoid output hang issue
  BlockServer/epics/archiver_manager.py
Labels: size/S
